import {
  app,
  BrowserWindow,
  ipcMain,
  dialog,
  BrowserWindowConstructorOptions,
  MessageBoxOptions,
  MessageBoxReturnValue,
} from "electron";
import fs from "fs/promises";
import * as path from "path";
import isDev from "electron-is-dev";
import { TestConfig, TestShiftData } from "./test/TestData";
import { format } from "date-fns";
import util from "./utils/util";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

async function IpcAction<T>(action: () => Promise<T>): Promise<IpcResponse<T>> {
  try {
    const data = await action();
    return { success: true, data };
  } catch (error) {
    return { success: false, error: error?.message ?? String(error) };
  }
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

ipcMain.handle(
  "read-file",
  async (
    _event,
    filePath: string,
    currentDirPath: boolean
  ): Promise<IpcResponse<string>> =>
    await IpcAction<string>(async () => {
      const p = currentDirPath ? path.join(__dirname, filePath) : filePath;
      const data = await fs.readFile(p, "utf-8");
      return data;
    })
);

ipcMain.handle(
  "write-file",
  async (
    _event,
    filePath: string,
    content: string,
    currentDirPath: boolean
  ): Promise<IpcResponse<void>> =>
    await IpcAction<void>(async () => {
      const p = currentDirPath ? path.join(__dirname, filePath) : filePath;
      await fs.writeFile(p, content, "utf-8");
    })
);

ipcMain.handle("open-file-dialog", async () => {
  const result = await dialog.showOpenDialog({
    properties: ["openFile"],
    filters: [
      { name: "Text Files", extensions: ["txt", "md"] },
      { name: "All Files", extensions: ["*"] },
    ],
  });

  if (result.canceled || result.filePaths.length === 0) {
    return null;
  }

  return result.filePaths[0]; // 선택된 파일 경로
});

ipcMain.handle(
  "open-editor",
  async (
    _event,
    brand: string,
    area: string,
    restaurant: string,
    shift: string
  ): Promise<IpcResponse<number>> =>
    await IpcAction(async () => {
      return openWindow(`/editor/${brand}/${area}/${restaurant}/${shift}`, {
        height: 755,
        width: 1260,
        title: "Shift Editor",
      });
    })
);

ipcMain.handle(
  "open-dev-tool",
  async (_event, winId: number): Promise<IpcResponse<void>> =>
    await IpcAction(async () => {
      const win = BrowserWindow.fromId(winId);
      win.webContents.openDevTools({ mode: "detach" });
    })
);

const getSubDirectories = async (paths: string) => {
  return (
    await Promise.all(
      (await fs.readdir(paths)).map(async (entry) =>
        (await fs.stat(path.join(paths, entry))).isDirectory() ? entry : null
      )
    )
  ).filter((entry): entry is string => entry !== null);
};
const getFiles = async (paths: string) => {
  return (
    await Promise.all(
      (await fs.readdir(paths)).map(async (entry) =>
        !(await fs.stat(path.join(paths, entry))).isDirectory() ? entry : null
      )
    )
  ).filter((entry): entry is string => entry !== null);
};
ipcMain.handle(
  "get-data-info",
  async (_event): Promise<IpcResponse<GetDataInfoResponse>> =>
    await IpcAction(async () => {
      let result: GetDataInfoResponse = { brands: null };
      const dataDirPath = path.join(__dirname, "data");
      console.log(__dirname);
      // ./data 탐색 (디렉토리만) (Brands)
      const dataDir = await getSubDirectories(path.join(dataDirPath));

      // ./data/.../ 탐색 (Areas)
      const areas = await Promise.all(
        dataDir
          .filter(async (brand) =>
            (await fs.stat(path.join(dataDirPath, brand))).isDirectory()
          )
          .map(async (brand) => [
            brand,
            {
              // config:
              //   JSON.parse(
              //     await fs.readFile(
              //       path.join(dataDirPath, brand, "brand.json"),
              //       "utf-8"
              //     )
              //   ) ?? {},
              areas: Object.fromEntries(
                await Promise.all(
                  (await getSubDirectories(path.join(dataDirPath, brand))).map(
                    async (area) => [
                      area,
                      Object.fromEntries(
                        await Promise.all(
                          (
                            await getSubDirectories(
                              path.join(dataDirPath, brand, area)
                            )
                          ).map(async (restaurant) => [
                            restaurant,
                            (
                              await getFiles(
                                path.join(dataDirPath, brand, area, restaurant)
                              )
                            ).filter((x) => x !== "workers.json"),
                          ])
                        )
                      ),
                    ]
                  )
                )
              ),
            },
          ])
      );

      result.brands = Object.fromEntries(areas);
      return result;
    })
);

ipcMain.handle(
  "get-brand-config",
  async (_event, brand: string): Promise<IpcResponse<BrandConfig>> =>
    await IpcAction(async () =>
      JSON.parse(
        await fs.readFile(
          path.join(__dirname, "data", brand, "brand.json"),
          "utf-8"
        )
      )
    )
);

ipcMain.handle(
  "get-shift",
  async (
    _event,
    brand: string,
    area: string,
    restaurant: string,
    shift: string
  ): Promise<IpcResponse<Shift>> =>
    await IpcAction(async () => ({
      workers: JSON.parse(
        await fs.readFile(
          path.join(__dirname, "data", brand, area, restaurant, "workers.json"),
          "utf-8"
        )
      ),
      week: JSON.parse(
        await fs.readFile(
          path.join(
            __dirname,
            "data",
            brand,
            area,
            restaurant,
            `${shift}.json`
          ),
          "utf-8"
        )
      ),
      firstDate: util.parseYYYYMMDD(shift),
    }))
);

ipcMain.handle(
  "get-directoryinfo",
  async (_event, paths: string): Promise<IpcResponse<DirectoryInfo>> =>
    await IpcAction(async () => {
      const getDirs = async (p: string): Promise<DirectoryInfo> => {
        const entries = await fs.readdir(p);
        const dirs = (
          await Promise.all(
            entries.map(async (f) => {
              const stat = await fs.stat(path.join(p, f));
              return stat.isDirectory() ? f : null;
            })
          )
        ).filter((entry): entry is string => entry !== null);

        const files = (
          await Promise.all(
            entries.map(async (f) => {
              const stat = await fs.stat(path.join(p, f));
              return stat.isFile() ? f : null;
            })
          )
        ).filter((entry): entry is string => entry !== null);

        return {
          directories: Object.fromEntries(
            await Promise.all(
              dirs
                .filter((f): f is string => f !== null)
                .map(async (f) => [f, await getDirs(path.join(p, f))])
            )
          ),
          files: files,
        };
      };

      return await getDirs(path.join(__dirname, paths));
    })
);

ipcMain.handle(
  "show-msgbox",
  async (
    _event,
    option: MessageBoxOptions
  ): Promise<IpcResponse<MessageBoxReturnValue>> =>
    await IpcAction(async () => {
      return dialog.showMessageBox(option);
    })
);

ipcMain.handle(
  "set-window-size",
  async (
    _event,
    winId: number,
    args: { width: number; height: number }
  ): Promise<IpcResponse<void>> =>
    await IpcAction(async () => {
      const win = BrowserWindow.fromId(winId);
      const { width, height } = args;

      const [frameWidth, frameHeight] = win.getSize();
      const [contentWidth, contentHeight] = win.getContentSize();

      const extraWidth = frameWidth - contentWidth;
      const extraHeight = frameHeight - contentHeight;
      // const bounds = win.getBounds();
      // win.setBounds({
      //   x: bounds.x,
      //   y: bounds.y,
      //   width: Math.ceil(width + extraWidth),
      //   height: Math.ceil(height + extraHeight),
      // });
      win.setContentSize(width, height);
    })
);

const openWindow = (
  view?: string,
  options?: BrowserWindowConstructorOptions
): number => {
  const baseUrl = isDev
    ? "http://localhost:3000/main_window"
    : `file://${path.join(__dirname, "../renderer/main_window/index.html")}`;

  const window = new BrowserWindow({
    ...options,
    resizable: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  const index = window.id;
  const query = new URLSearchParams({ winId: `${index}` }).toString();
  window.loadURL(`${baseUrl}${view ? `#${view}` : ""}?${query}`);
  // window.webContents.openDevTools();
  return index;
};

const createWindow = (): void => {
  openWindow(undefined, { height: 800, width: 1500 });
  // const mainWindow = new BrowserWindow({
  //   height: 800,
  //   width: 1500,
  //   webPreferences: {
  //     preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
  //     contextIsolation: true,
  //     nodeIntegration: false,
  //   },
  // });
  // mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

const onReady = async (): Promise<void> => {
  const dataPath = path.join(__dirname, "data");
  let isExist: boolean;

  try {
    const stats = await fs.stat(dataPath);
    isExist = stats.isDirectory();
  } catch (error) {
    isExist = false;
  }

  if (!isExist) await fs.mkdir(dataPath);

  // TESTDATA

  const brand = path.join(dataPath, "KFC");
  await fs.mkdir(brand);
  await fs.writeFile(
    path.join(brand, "brand.json"),
    JSON.stringify(TestConfig.Brand, null, 2)
  );

  const area = path.join(brand, "TestArea");
  await fs.mkdir(area);

  await fs.mkdir(path.join(area, "TestStation"));
  await fs.writeFile(
    path.join(area, "TestStation", "workers.json"),
    JSON.stringify(TestShiftData.workers, null, 2)
  );
  await fs.writeFile(
    path.join(
      area,
      "TestStation",
      `${format(TestShiftData.firstDate, "yyyyMMdd")}.json`
    ),
    JSON.stringify(TestShiftData.week, null, 2)
  );
};

app.on("ready", onReady);
app.on("ready", createWindow);
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
