import {
  app,
  BrowserWindow,
  ipcMain,
  dialog,
  BrowserWindowConstructorOptions,
  MessageBoxOptions,
  MessageBoxReturnValue,
  globalShortcut,
} from "electron";
import fs, { constants } from "fs/promises";
import * as path from "path";
import isDev from "electron-is-dev";
import { TestConfig, TestShiftData } from "./test/TestData";
import { format } from "date-fns";
import util from "./utils/util";
import ShiftF from "./data/ShiftF";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

async function IpcAction<T>(action: () => Promise<T>): Promise<IpcResponse<T>> {
  try {
    const data = await action();
    return { success: true, data };
  } catch (error) {
    return { success: false, error: error?.message ?? String(error) };
  }
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

ipcMain.handle(
  "read-file",
  async (
    _event,
    filePath: string,
    currentDirPath: boolean
  ): Promise<IpcResponse<string>> =>
    await IpcAction<string>(async () => {
      const p = currentDirPath ? path.join(__dirname, filePath) : filePath;
      const data = await fs.readFile(p, "utf-8");
      return data;
    })
);

ipcMain.handle(
  "write-file",
  async (
    _event,
    filePath: string,
    content: string,
    currentDirPath: boolean
  ): Promise<IpcResponse<void>> =>
    await IpcAction<void>(async () => {
      const p = currentDirPath ? path.join(__dirname, filePath) : filePath;
      await fs.writeFile(p, content, "utf-8");
    })
);

ipcMain.handle("open-file-dialog", async () => {
  const result = await dialog.showOpenDialog({
    properties: ["openFile"],
    filters: [
      { name: "Text Files", extensions: ["txt", "md"] },
      { name: "All Files", extensions: ["*"] },
    ],
  });

  if (result.canceled || result.filePaths.length === 0) {
    return null;
  }

  return result.filePaths[0]; // 선택된 파일 경로
});

ipcMain.handle(
  "open-editor",
  async (
    _event,
    { brand, area, restaurant, date, shift }
  ): Promise<IpcResponse<number>> =>
    await IpcAction(async () => {
      const winId = openWindow(
        `/editor/${brand}/${area}/${restaurant}/${date}/${shift}`,
        {
          height: 800,
          width: 1300,
          title: "Shift Editor",
          resizable: false,
        }
      );
      const win = BrowserWindow.fromId(winId);

      win.on("close", (e) => {
        e.preventDefault();
        win.webContents.send("ask-save");
      });

      // win.webContents.on("will-prevent-unload", (event) => {
      //   event.preventDefault();
      //   win.webContents.send("ask-save");
      // });

      return winId;
    })
);

ipcMain.handle(
  "open-dev-tool",
  async (_event, winId: number): Promise<IpcResponse<void>> =>
    await IpcAction(async () => {
      const win = BrowserWindow.fromId(winId);
      win.webContents.openDevTools({ mode: "detach" });
    })
);

const getSubDirectories = async (paths: string) => {
  return (
    await Promise.all(
      (await fs.readdir(paths)).map(async (entry) =>
        (await fs.stat(path.join(paths, entry))).isDirectory() ? entry : null
      )
    )
  ).filter((entry): entry is string => entry !== null);
};
const getFiles = async (paths: string) => {
  return (
    await Promise.all(
      (await fs.readdir(paths)).map(async (entry) =>
        !(await fs.stat(path.join(paths, entry))).isDirectory() ? entry : null
      )
    )
  ).filter((entry): entry is string => entry !== null);
};
ipcMain.handle(
  "get-data-info",
  async (_event): Promise<IpcResponse<GetDataInfoResponse>> =>
    await IpcAction(async () => {
      const dataDirPath = path.join(__dirname, "data");
      const brandDirs = await getSubDirectories(dataDirPath);

      const brandEntries = await Promise.all(
        brandDirs.map(async (brand) => {
          const brandPath = path.join(dataDirPath, brand);
          if (!(await fs.stat(brandPath)).isDirectory()) return null;

          const areaDirs = await getSubDirectories(brandPath);
          const areaEntries = await Promise.all(
            areaDirs.map(async (area) => {
              const areaPath = path.join(brandPath, area);
              const restaurantDirs = await getSubDirectories(areaPath);
              const restaurantEntries = await Promise.all(
                restaurantDirs.map(async (restaurant) => {
                  const restaurantPath = path.join(areaPath, restaurant);
                  const dateDirs = await getSubDirectories(restaurantPath);
                  const dateEntries = await Promise.all(
                    dateDirs.map(async (date) => {
                      const datePath = path.join(restaurantPath, date);
                      const files = await getFiles(datePath);
                      return [date, files];
                    })
                  );
                  return [restaurant, Object.fromEntries(dateEntries)];
                })
              );
              return [area, Object.fromEntries(restaurantEntries)];
            })
          );
          return [brand, Object.fromEntries(areaEntries)];
        })
      );

      return Object.fromEntries(brandEntries.filter(Boolean));
    })
);

ipcMain.handle(
  "get-brand-config",
  async (_event, brand: string): Promise<IpcResponse<BrandConfig>> =>
    await IpcAction(async () =>
      JSON.parse(
        await fs.readFile(
          path.join(__dirname, "data", brand, "brand.json"),
          "utf-8"
        )
      )
    )
);

ipcMain.handle(
  "get-shift",
  async (
    _event,
    { brand, area, restaurant, date, shift }
  ): Promise<IpcResponse<Shift>> =>
    await IpcAction(async () => {
      const workerPath = path.join(
        __dirname,
        "data",
        brand,
        area,
        restaurant,
        "workers.json"
      );
      const weekPath = path.join(
        __dirname,
        "data",
        brand,
        area,
        restaurant,
        date,
        `${shift}.json`
      );

      const workers = JSON.parse(await fs.readFile(workerPath, "utf-8"));
      let week: Week;
      try {
        await fs.access(weekPath, constants.F_OK);
        week = JSON.parse(await fs.readFile(weekPath, "utf-8"));
      } catch {
        const newWeek = {
          color: "black",
          descriptions: "",
          expectedSales: 0,
          expectedTC: {
            0: 0,
            1: 0,
            2: 0,
            3: 0,
            4: 0,
            5: 0,
            6: 0,
            7: 0,
            8: 0,
            9: 0,
            10: 0,
            11: 0,
            12: 0,
            13: 0,
            14: 0,
            15: 0,
            16: 0,
            17: 0,
            18: 0,
            19: 0,
            20: 0,
            21: 0,
            22: 0,
            23: 0,
            24: 0,
          },
          targetSales: 0,
          targetUsageTime: 0,
          workers: {},
        };
        week = {
          days: {
            mon: { ...newWeek },
            tue: { ...newWeek },
            wed: { ...newWeek },
            thu: { ...newWeek },
            fri: { ...newWeek },
            sat: { ...newWeek, color: "blue" },
            sun: { ...newWeek, color: "red" },
          },
        };
      }

      const res = {
        workers: workers,
        week: week,
        firstDate: util.parseYYYYMMDD(date),
      };

      return res;
    })
);

ipcMain.handle(
  "get-directoryinfo",
  async (_event, paths: string): Promise<IpcResponse<DirectoryInfo>> =>
    await IpcAction(async () => {
      const getDirs = async (p: string): Promise<DirectoryInfo> => {
        const entries = await fs.readdir(p);
        const dirs = (
          await Promise.all(
            entries.map(async (f) => {
              const stat = await fs.stat(path.join(p, f));
              return stat.isDirectory() ? f : null;
            })
          )
        ).filter((entry): entry is string => entry !== null);

        const files = (
          await Promise.all(
            entries.map(async (f) => {
              const stat = await fs.stat(path.join(p, f));
              return stat.isFile() ? f : null;
            })
          )
        ).filter((entry): entry is string => entry !== null);

        return {
          directories: Object.fromEntries(
            await Promise.all(
              dirs
                .filter((f): f is string => f !== null)
                .map(async (f) => [f, await getDirs(path.join(p, f))])
            )
          ),
          files: files,
        };
      };

      return await getDirs(path.join(__dirname, paths));
    })
);

ipcMain.handle(
  "show-msgbox",
  async (
    _event,
    option: MessageBoxOptions,
    winId: number
  ): Promise<IpcResponse<MessageBoxReturnValue>> =>
    await IpcAction(async () => {
      if (winId === -1) return dialog.showMessageBox({ ...option });
      else
        return dialog.showMessageBox(BrowserWindow.fromId(winId), {
          ...option,
        });
    })
);

ipcMain.handle(
  "set-window-size",
  async (
    _event,
    winId: number,
    args: { width: number; height: number }
  ): Promise<IpcResponse<void>> =>
    await IpcAction(async () => {
      const win = BrowserWindow.fromId(winId);
      if (!win) return;
      const { width, height } = args;
      const resizable = win.resizable;
      win.setResizable(true);
      win.setContentSize(width, height);
      win.setResizable(resizable);
    })
);

ipcMain.handle(
  "close-window",
  async (_event, winId: number): Promise<IpcResponse<void>> =>
    await IpcAction(async () => {
      const win = BrowserWindow.fromId(winId);
      if (!win) return;

      win.destroy();
    })
);

ipcMain.handle(
  "register-shortcut",
  async (
    _event,
    winId: number,
    items: [shortcut: string, channel: string][]
  ): Promise<IpcResponse<void>> =>
    await IpcAction(async () => {
      const win = BrowserWindow.fromId(winId);
      if (!win) throw new Error("invalid window id");

      items.forEach(([scut, ch]) => {
        const sendChannel = `shortcut-${ch}`;
        globalShortcut.register(scut, () => {
          try {
            if (
              win &&
              win?.isFocused() &&
              !win.isDestroyed() &&
              !win.webContents.isDestroyed()
            ) {
              win?.webContents?.send(sendChannel);
            }
          } catch {}
        });
      });
    })
);

const openWindow = (
  view?: string,
  options?: BrowserWindowConstructorOptions
): number => {
  const baseUrl = isDev
    ? "http://localhost:3000/main_window"
    : `file://${path.join(__dirname, "../renderer/main_window/index.html")}`;

  const window = new BrowserWindow({
    ...options,
    useContentSize: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  window.setMenu(null);
  const index = window.id;
  const query = new URLSearchParams({ winid: `${index}` }).toString();
  window.loadURL(`${baseUrl}${view ? `#${view}` : ""}?${query}`);
  // window.webContents.openDevTools();
  return index;
};

const createWindow = (): void => {
  openWindow(undefined, { height: 800, width: 1500 });
  // const mainWindow = new BrowserWindow({
  //   height: 800,
  //   width: 1500,
  //   webPreferences: {
  //     preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
  //     contextIsolation: true,
  //     nodeIntegration: false,
  //   },
  // });
  // mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

const onReady = async (): Promise<void> => {
  const dataPath = path.join(__dirname, "data");
  let isExist: boolean;

  try {
    const stats = await fs.stat(dataPath);
    isExist = stats.isDirectory();
  } catch (error) {
    isExist = false;
  }

  if (!isExist) await fs.mkdir(dataPath);

  // TESTDATA

  const brand = path.join(dataPath, "KFC");
  await fs.mkdir(brand);
  await fs.writeFile(
    path.join(brand, "brand.json"),
    JSON.stringify(TestConfig.Brand, null, 2)
  );

  const area = path.join(brand, "TestArea");
  await fs.mkdir(area);

  const rest = path.join(area, "TestStation");
  await fs.mkdir(rest);
  await fs.writeFile(
    path.join(rest, "workers.json"),
    JSON.stringify(TestShiftData.workers, null, 2)
  );
  const date = path.join(rest, format(TestShiftData.firstDate, "yyyyMMdd"));
  await fs.mkdir(date);
  await fs.writeFile(
    path.join(date, `test1.json`),
    JSON.stringify(TestShiftData.week, null, 2)
  );
};

const onWillQuit = () => {
  globalShortcut.unregisterAll();
};

app.on("will-quit", onWillQuit);

app.on("ready", onReady);
app.on("ready", createWindow);
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
